/* This file was autogenerated by openCONFIGURATOR-1.2.2 on 10-Jan-2013 21:21:41 */
#ifndef XAP_h
#define XAP_h

# define COMPUTED_PI_OUT_SIZE 36
typedef struct 
{
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_01:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_02:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_03:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_04:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_05:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_06:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_07:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_08:32;
	unsigned CN1_M00_Digital_Input_32_Bit_DWORD_09:32;
} PI_OUT;

# define COMPUTED_PI_IN_SIZE 16
typedef struct 
{
	unsigned CN1_M00_Digital_Ouput_32_Bit_DWORD_01:32;
	unsigned CN1_M00_Digital_Ouput_32_Bit_DWORD_02:32;
	unsigned CN1_M00_Digital_Ouput_32_Bit_DWORD_03:32;
	unsigned CN1_M00_Digital_Ouput_32_Bit_DWORD_04:32;
} PI_IN;

#endif